#!/bin/bash

#SBATCH --nodes=12
#SBATCH --ntasks=12
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=2500
#SBATCH --error=error.txt
#SBATCH --output=output.txt
#SBATCH --time=36:00:00


mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 0.01
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 0.1
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 0.3
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 0.75
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.0
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.1
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.2
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.3
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.31
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.32
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.33
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.34
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.35
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.36
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.37
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.38
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.39
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.40
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.41
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.42
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.43
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.44
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.45
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.46
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.47
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.48
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.49
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.50
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.51
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.52
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.53
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.54
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.55
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.56
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.57
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.58
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.59
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.60
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.61
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.62
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.63
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.64
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.65
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.66
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.67
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.68
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.69
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.70
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.8
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 1.9
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 2.0
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 3.0
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 5.0
mpirun -bind-to core -map-by core -n 1 .././programs/HeisenbergMPI 10.0
